CREATE TABLE [dbo].[Groups] (

	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (NEWSEQUENTIALID()),
	[ParentId] UNIQUEIDENTIFIER NULL,
	[Name] NVARCHAR(100) NOT NULL

	CONSTRAINT [FK_Groups_ToGroups] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Groups]([Id])    
)

GO