CREATE TABLE [dbo].[Pages] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (NEWSEQUENTIALID()), 
    [Name] NVARCHAR(250) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
	[OrderNo] INT NOT NULL, 
	[SurveyId] UNIQUEIDENTIFIER NOT NULL, 
	CONSTRAINT [FK_Pages_SurveySections] FOREIGN KEY ([SurveyId]) REFERENCES [dbo].[SurveySections]([Id]), 
);
