CREATE TABLE [dbo].[Respondents] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (NEWSEQUENTIALID()),  
	[UserId] UNIQUEIDENTIFIER NULL, 
	CONSTRAINT [FK_Respondents_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id])
);
