CREATE TABLE [dbo].[SurveySections] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (NEWSEQUENTIALID()), 
    [Name] NVARCHAR(500) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
	[DateCreated] DATETIME NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_SurveySections_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]), 
);
